Написать программу, принимающую на вход две нуклеотидные последовательности, и вычисляющую score оптимального выравнивания с помощью алгоритма Нидлмана-Вунша, используя матрицу штрафов DNAfull и аффинный штраф за гэп(𝑑= 10, 𝑒= 0.5).

In [14]:
import numpy as np

seq1 = 'CTA'
seq2 = 'CTCGA'

# Make matrices

S_matrix = np.zeros((len(seq1)+1, len(seq2)+1))
A_matrix = np.zeros((len(seq1), len(seq2)))
B_matrix = np.zeros((len(seq1), len(seq2)))
match_matrix = np.zeros((len(seq1), len(seq2)))


match_score = 5
mismatch_score = -4
d = 10
e = 0.5

for i in range(len(seq2)):
    for j in range (len(seq1)):
        if seq2[i] == seq1[j]:
            match_matrix[j][i]=match_score
        else:
            match_matrix[j][i]=mismatch_score
# print (match_matrix)

# Filling S matrix with certain conditions
# Lines
for i in range(0, len(seq1)+1):
    S_matrix[i][0] = -d-(i-1)*e
# Columns
for j in range(0, len(seq2)+1):
    S_matrix[0][j] = -d-(j-1)*e
S_matrix[0][0] = 0


# Filling A and B matrices
for i in range(1, len(seq2)+1):
    A_matrix[0][i-1] = S_matrix[0][i]-10
for j in range(1, len(seq1)+1):
    B_matrix[j-1][0] = S_matrix[j][0]-10
k=0

for i in range (1, len(seq1)+1):
    for j in range(1, len(seq2)+1):
        S_matrix[i][j] = max (S_matrix[i-1][j-1]+match_matrix[i-1][j-1],
                              A_matrix[i-1][j-1],
                              B_matrix[i-1][j-1])        
        
        if i<len(seq1) and j<len(seq2):
            A_matrix[i][j-1] = max(A_matrix[i-1][j-1]-e,
                                   S_matrix[i+1][j]-d)
            B_matrix[i-1][j] = max(B_matrix[i][j-1]-e,
                                   S_matrix[i][j+1]-d)      

A_matrix[i][j-1] = max(A_matrix[i-1][j-1]-e,
                       S_matrix[i+1][j]-d)

B_matrix[i-1][j] = max(B_matrix[i][j-1]-e,
                       S_matrix[i][j+1]-d)

S_matrix[i][j] = max (S_matrix[i-1][j-1]+match_matrix[i-1][j-1],
                      A_matrix[i-1][j-1],
                      B_matrix[i-1][j-1])  
'''
for i in range (1, len(seq1)-1):
    for j in range(1, len(seq2)-1):

            S_matrix[i+1][j+1] = max(S_matrix[i][j]+match_matrix[i][j],
                                     A_matrix[i][j],
                                     B_matrix[i][j])
            
       
            A_matrix[i+1][j] = max(A_matrix[i][j]-e,
                                   S_matrix[i+1][j+1]-d)
            
            B_matrix[i][j+1] = max(B_matrix[i][j]-e,
                               S_matrix[i+1][j+1]-d)
'''



print(A_matrix, '\n')
print(B_matrix, '\n')
print(S_matrix, '\n')


[[-20.  -20.5 -21.  -21.5 -22. ]
 [-10.  -10.  -10.  -10.    0. ]
 [-10.  -10.  -10.  -10.    0. ]] 

[[-20.  -10.   -0.5  -0.5  -0.5]
 [-20.5 -10.   -0.5  -0.5  -0.5]
 [-21.    0.    0.    0.    0. ]] 

[[  0.  -10.  -10.5 -11.  -11.5 -12. ]
 [-10.    5.  -10.   -0.5  -0.5  -0.5]
 [-10.5 -10.   10.   -0.5  -0.5   0. ]
 [-11.  -10.    0.    6.    0.    4.5]] 



In [5]:
x='kjewk'
for i in range(len(x)-1):
    print (i)

0
1
2
3
